# Generated by Django 4.2.28 on 2026-02-11 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
    ]
