# Generated by Django 4.2.28 on 2026-02-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productattribute_productattributevalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Категории'},
        ),
    ]
