# Generated by Django 4.2.28 on 2026-02-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-is_featured', 'name'], 'verbose_name_plural': 'Товары'},
        ),
    ]
