# Generated by Django 4.2.28 on 2026-02-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.import_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название импорта')),
                ('file', models.FileField(help_text='Поддерживаемые форматы: .xlsx, .xls, .csv', upload_to=products.import_models.import_file_path, verbose_name='Файл Excel')),
                ('import_type', models.CharField(choices=[('create', 'Только создание'), ('update', 'Только обновление'), ('create_update', 'Создание и обновление')], default='create_update', max_length=20, verbose_name='Тип импорта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('partial', 'Частично завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='imports/logs/', verbose_name='Лог импорта')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('skip_existing', models.BooleanField(default=False, verbose_name='Пропускать существующие (по SKU)')),
                ('update_images', models.BooleanField(default=False, verbose_name='Обновлять изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Категория по умолчанию')),
            ],
            options={
                'verbose_name': 'Импорт товаров',
                'verbose_name_plural': 'Импорты товаров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='Номер строки')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Название товара')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('created', 'Создан'), ('updated', 'Обновлен'), ('error', 'Ошибка'), ('skipped', 'Пропущен')], max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Исходные данные')),
                ('import_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='products.productimport', verbose_name='Импорт')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['row_number'],
            },
        ),
    ]
