# Generated by Django 4.2.28 on 2026-02-11 06:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('display_type', models.CharField(choices=[('grid', 'Сетка'), ('masonry', 'Плитка (Masonry)'), ('slider', 'Слайдер'), ('carousel', 'Карусель'), ('lightbox', 'Лайтбокс галерея')], default='grid', max_length=20, verbose_name='Тип отображения')),
                ('columns', models.PositiveSmallIntegerField(default=3, help_text='Количество колонок при отображении сеткой', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Колонки (для сетки)')),
                ('gap', models.PositiveSmallIntegerField(default=20, verbose_name='Отступ между изображениями (px)')),
                ('autoplay', models.BooleanField(default=True, help_text='Для слайдера и карусели', verbose_name='Автопрокрутка')),
                ('autoplay_speed', models.PositiveSmallIntegerField(default=3000, help_text='3000 = 3 секунды', verbose_name='Скорость автопрокрутки (мс)')),
                ('infinite_loop', models.BooleanField(default=True, verbose_name='Бесконечная прокрутка')),
                ('show_arrows', models.BooleanField(default=True, verbose_name='Показывать стрелки навигации')),
                ('show_dots', models.BooleanField(default=True, verbose_name='Показывать точки навигации')),
                ('slides_to_show', models.PositiveSmallIntegerField(default=1, help_text='Для карусели - сколько слайдов показывать', verbose_name='Слайдов одновременно')),
                ('slides_to_scroll', models.PositiveSmallIntegerField(default=1, verbose_name='Слайдов за раз')),
                ('image_height', models.PositiveSmallIntegerField(blank=True, help_text='Оставьте пустым для оригинальных пропорций', null=True, verbose_name='Фиксированная высота (px)')),
                ('object_fit', models.CharField(choices=[('cover', 'Cover - заполнить'), ('contain', 'Contain - вписать'), ('fill', 'Fill - растянуть')], default='cover', max_length=20, verbose_name='Обрезка изображений')),
                ('border_radius', models.PositiveSmallIntegerField(default=0, verbose_name='Скругление углов (px)')),
                ('shadow', models.BooleanField(default=False, verbose_name='Тень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/%Y/%m/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст (SEO)')),
                ('description', models.TextField(blank=True, verbose_name='Описание / Подпись')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Подпись на слайде')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, verbose_name='Ссылка кнопки')),
                ('overlay_color', models.CharField(default='#000000', help_text='HEX цвет, например #000000', max_length=7, verbose_name='Цвет оверлея')),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Прозрачность оверлея')),
                ('text_position', models.CharField(choices=[('center', 'По центру'), ('left', 'Слева'), ('right', 'Справа'), ('bottom-left', 'Снизу слева'), ('bottom-center', 'Снизу по центру'), ('bottom-right', 'Снизу справа')], default='center', max_length=20, verbose_name='Позиция текста')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galleries.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
