# Generated by Django 4.2.28 on 2026-02-11 11:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_recipients', models.TextField(default='admin@example.com', help_text='Укажите email через запятую', verbose_name='Email получателей')),
                ('notify_telegram', models.BooleanField(default=False, verbose_name='Уведомлять в Telegram')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, verbose_name='Токен бота Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Chat ID Telegram')),
                ('max_file_size', models.PositiveIntegerField(default=10, verbose_name='Максимальный размер файла (MB)')),
                ('allowed_extensions', models.CharField(default='jpg,jpeg,png,gif,pdf', max_length=200, verbose_name='Разрешенные расширения')),
                ('enable_captcha', models.BooleanField(default=False, verbose_name='Включить капчу')),
            ],
            options={
                'verbose_name': 'Настройки обратной связи',
                'verbose_name_plural': 'Настройки обратной связи',
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +79991234567 или 89991234567', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('message_type', models.CharField(choices=[('general', 'Общий вопрос'), ('support', 'Техподдержка'), ('sales', 'Отдел продаж'), ('partnership', 'Партнерство'), ('complaint', 'Жалоба'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Тип обращения')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, help_text='Допустимые форматы: JPG, PNG, GIF, PDF. Максимальный размер: 10MB', null=True, upload_to=feedback.models.feedback_file_path, verbose_name='Прикрепленный файл')),
                ('privacy_policy_accepted', models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности')),
                ('privacy_policy_url', models.URLField(blank=True, verbose_name='URL политики конфиденциальности (на момент отправки)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, verbose_name='Страница отправки')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('answered', 'Отвечено'), ('closed', 'Закрыто'), ('spam', 'Спам')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('email_error', models.TextField(blank=True, verbose_name='Ошибка отправки email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Ответил')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
    ]
